// Pseudo-randomly generated
const List<String> pizzaToppings = [
  '24-karat gold leaves',
  'alfredo',
  'almonds',
  'anchovies',
  'artichoke hearts',
  'artichokes',
  'arugula',
  'avocado',
  'baby leeks',
  'bacon',
  'basil',
  'bay leaf',
  'bbq chicken',
  'bbq sauce',
  'bean sprouts',
  'beet pesto',
  'beetroot',
  'black beans',
  'black olives',
  'brie',
  'broccoli',
  'brussel sprouts',
  'bushmeat',
  'cajun prawn',
  'calamari',
  'camel',
  'canadian bacon',
  'capicolla',
  'caramelized onions',
  'cardamon',
  'carrot',
  'cashew nuts',
  'cauliflower',
  'century egg',
  'cheddar',
  'cheez whiz',
  'cherry tomatoes',
  'cheval',
  'chicken masala',
  'chicken tikka',
  'chicken tikka masala',
  'chorizo',
  'cilantro',
  'clams',
  'colby',
  'colby jack',
  'corn',
  'crab meat',
  'crocodile',
  'crushed red pepper',
  'crushed walnuts',
  'cumin',
  'dill',
  'dill pickles',
  'dried tomatoes',
  'duck',
  'egg',
  'eggplant',
  'emu',
  'feta',
  'feta cheese',
  'fig',
  'fig jam',
  'fontina',
  'frogs legs',
  'fungi',
  'fungi carciofi',
  'garlic',
  'german sausage',
  'goat cheese',
  'gorgonzola',
  'greek yogurt',
  'green peppers',
  'ground beef',
  'gruyère cheese',
  'ham',
  'honey',
  'honey cured ham',
  'hot sauce',
  'kalamata olives',
  'kimchi',
  'lamb',
  'leeks',
  'lettuce',
  'lobster',
  'lobster tails',
  'manchego',
  'meatballs',
  'monterey jack',
  'mozzarella',
  'muenster',
  'muktuk',
  'mushrooms',
  'olive oil',
  'onions',
  'orange bell pepper',
  'oregano',
  'oysters',
  'parley',
  'peanut crumbles',
  'pecans',
  'pepper',
  'pepper jack',
  'pepperoni',
  'pesto',
  'pickled ginger',
  'pine nuts',
  'porcini mushrooms',
  'potato',
  'prawns',
  'prosciutto',
  'provolone',
  'quail eggs',
  'ranch dressing',
  'red beans',
  'red bell pepper',
  'red onions',
  'red peppers',
  'red sauce',
  'roast cauliflower',
  'roasted eggplant',
  'roasted garlic',
  'roasted peppers',
  'roasted red peppers',
  'rocky mountain oysters',
  'salami',
  'salmon',
  'sausage',
  'scallions',
  'serrano ham',
  'shark fins',
  'shaved coconut',
  'shredded chicken',
  'shrimp',
  'sliced almonds',
  'smoked gouda',
  'smoked salmon',
  'snow peas',
  'sopressata',
  'southern fried rattlesnake',
  'spinach',
  'squid',
  'steak tartare',
  'stroganoff',
  'surstromming',
  'sweet chili sauce',
  'sweet corn',
  'sweet potato',
  'teriyaki chicken',
  'teriyaki sauce',
  'thyme',
  'tiger prawns',
  'tomato',
  'tripe',
  'truffles',
  'tuna',
  'turkey',
  'venison',
  'watercress',
  'white pizza sauce',
  'yellow bell pepper',
  'yellow peppers',
  'yellow squash',
  'zucchini'
];
