apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopherpizza-workers
spec:
  selector:
    matchLabels:
      app: gopherpizza
  replicas: 2
  template:
    metadata:
      labels:
        app: gopherpizza 
    spec:
      containers:
      - name: gopherpizza
        image: gopherpizza:latest
        imagePullPolicy: Never
